Repository TraviTago/tago-api, pull requests merged in 2023-09, with the labels that each got.

#49 fix: 여행 상세 조회 응답에 isJoined 필드 추가
  api/src/main/java/com/tago/api/common/mapper/PlaceDtoMapper.java
  api/src/main/java/com/tago/api/common/mapper/TripStatusDtoMapper.java
  api/src/main/java/com/tago/api/common/util/TimeUtil.java
  api/src/main/java/com/tago/api/place/application/PlaceService.java
  api/src/main/java/com/tago/api/place/dto/response/PlaceInfoResponse.java
  api/src/main/java/com/tago/api/trip/application/TripPlaceService.java
  api/src/main/java/com/tago/api/trip/application/TripService.java
  api/src/main/java/com/tago/api/trip/dto/response/TripGetOneResponse.java
  api/src/main/java/com/tago/api/trip/dto/response/TripStatusResponse.java
  api/src/main/java/com/tago/api/trip/presentation/TripController.java
  api/src/main/resources/data.sql
  docker/Dockerfile
  docker/docker-compose.elastic.yml
  domain/src/main/java/com/tago/domain/member/domain/vo/Gender.java
  domain/src/main/java/com/tago/domain/trip/domain/Trip.java
  domain/src/main/java/com/tago/domain/trip/repository/TripPlaceCustomRepository.java
  domain/src/main/java/com/tago/domain/trip/repository/impl/TripPlaceCustomRepositoryImpl.java
  domain/src/main/java/com/tago/domain/trip/service/TripPlaceQueryService.java
  domain/src/main/java/com/tago/domain/tripmember/dto/TripMemberDto.java
  domain/src/main/java/com/tago/domain/tripmember/repository/TripMemberRepository.java
  domain/src/main/java/com/tago/domain/tripmember/service/TripMemberQueryService.java
Labels: refactor, fix

#54 feat: slack 연동 기능 추가
  api/build.gradle
  api/src/main/java/com/tago/api/issue/application/IssueReportService.java
  api/src/main/java/com/tago/api/slack/application/SlackService.java
  api/src/main/java/com/tago/api/slack/dto/SlackMessageDto.java
  api/src/main/resources/application.yml
  domain/src/main/java/com/tago/domain/issue/dto/IssueDto.java
Labels: feature

#55 feat: trip 검색 api 구현
  api/src/main/java/com/tago/api/trip/application/TripGetService.java
  api/src/main/java/com/tago/api/trip/application/TripPlaceService.java
  api/src/main/java/com/tago/api/trip/application/TripSearchService.java
  api/src/main/java/com/tago/api/trip/presentation/TripGetApi.java
  api/src/main/java/com/tago/api/trip/presentation/TripSearchApi.java
  api/src/main/resources/data.sql
  domain/src/main/java/com/tago/domain/trip/domain/Trip.java
  domain/src/main/java/com/tago/domain/trip/repository/TripCustomRepository.java
  domain/src/main/java/com/tago/domain/trip/repository/impl/TripCustomRepositoryImpl.java
  domain/src/main/java/com/tago/domain/trip/service/TripQueryService.java
Labels: feature, refactor

#62 refactor: member, place tag 분리
  api/src/main/java/com/tago/api/common/mapper/MemberDtoMapper.java
  api/src/main/resources/schema.sql
  domain/src/main/java/com/tago/domain/common/error/ErrorCode.java
  domain/src/main/java/com/tago/domain/course/domain/Course.java
  domain/src/main/java/com/tago/domain/member/domain/Member.java
  domain/src/main/java/com/tago/domain/member/domain/MemberTag.java
  domain/src/main/java/com/tago/domain/member/domain/vo/MemberTags.java
  domain/src/main/java/com/tago/domain/member/domain/vo/Profile.java
  domain/src/main/java/com/tago/domain/member/repository/MemberCustomRepository.java
  domain/src/main/java/com/tago/domain/member/repository/MemberRepository.java
  domain/src/main/java/com/tago/domain/member/repository/impl/MemberCustomRepositoryImpl.java
  domain/src/main/java/com/tago/domain/member/service/MemberQueryService.java
  domain/src/main/java/com/tago/domain/member/service/MemberUpdateService.java
  domain/src/main/java/com/tago/domain/place/domain/PlaceTag.java
  domain/src/main/java/com/tago/domain/tag/domain/Tag.java
  domain/src/main/java/com/tago/domain/tag/exception/TagNotFoundException.java
  domain/src/main/java/com/tago/domain/tag/repository/TagRepository.java
  domain/src/main/java/com/tago/domain/tag/service/TagQueryHandler.java
  domain/src/main/java/com/tago/domain/trip/domain/Trip.java
Labels: refactor

#74 feat: GlobalExceptionHandler 구현, 프로필 수정 API 구현
  api/src/main/java/com/tago/api/auth/jwt/handler/JwtAuthenticationEntryPoint.java
  api/src/main/java/com/tago/api/common/dto/ErrorResponse.java
  api/src/main/java/com/tago/api/common/exception/MainPlaceNotFoundException.java
  api/src/main/java/com/tago/api/common/handler/GlobalExceptionHandler.java
  api/src/main/java/com/tago/api/common/mapper/CourseDtoMapper.java
  api/src/main/java/com/tago/api/course/dto/response/CourseRecommendResponse.java
  api/src/main/java/com/tago/api/member/application/MemberService.java
  api/src/main/java/com/tago/api/member/dto/request/MemberUpdateRequest.java
  api/src/main/java/com/tago/api/member/presentation/MemberApi.java
  api/src/main/java/com/tago/api/place/application/PlaceService.java
  api/src/main/java/com/tago/api/place/presentation/PlaceApi.java
  api/src/main/resources/data.sql
  domain/src/main/java/com/tago/domain/common/error/ErrorCode.java
  domain/src/main/java/com/tago/domain/common/error/ErrorResponse.java
  domain/src/main/java/com/tago/domain/course/exception/CourseNotFoundException.java
  domain/src/main/java/com/tago/domain/course/repository/impl/CourseCustomRepositoryImpl.java
  domain/src/main/java/com/tago/domain/member/domain/Member.java
  domain/src/main/java/com/tago/domain/member/domain/MemberTag.java
  domain/src/main/java/com/tago/domain/member/dto/MemberUpdateDto.java
  domain/src/main/java/com/tago/domain/member/service/MemberCreateService.java
  domain/src/main/java/com/tago/domain/member/service/MemberTagCreateService.java
  domain/src/main/java/com/tago/domain/member/service/MemberUpdateService.java
  domain/src/main/java/com/tago/domain/place/repository/impl/PlaceCustomRepositoryImpl.java
  domain/src/main/java/com/tago/domain/place/service/PlaceQueryService.java
  domain/src/main/java/com/tago/domain/tag/repository/TagCustomRepository.java
  domain/src/main/java/com/tago/domain/tag/repository/TagRepository.java
  domain/src/main/java/com/tago/domain/tag/repository/impl/TagCustomRepositoryImpl.java
  domain/src/main/java/com/tago/domain/tag/service/TagQueryHandler.java
Labels: feature

#82 feat: 집결지 정보 추가
  api/src/main/java/com/tago/api/common/mapper/TripStatusDtoMapper.java
  api/src/main/java/com/tago/api/trip/dto/response/TripStatusResponse.java
Labels: feature

#84 feat: Trip 생성 API 구현
  api/src/main/java/com/tago/api/auth/application/AuthService.java
  api/src/main/java/com/tago/api/auth/application/TokenReissueService.java
  api/src/main/java/com/tago/api/auth/jwt/JwtProvider.java
  api/src/main/java/com/tago/api/course/application/CourseService.java
  api/src/main/java/com/tago/api/infra/slack/application/SlackService.java
  api/src/main/java/com/tago/api/issue/application/IssueReportService.java
  api/src/main/java/com/tago/api/member/application/MemberService.java
  api/src/main/java/com/tago/api/place/application/PlaceService.java
  api/src/main/java/com/tago/api/trip/application/TripGetService.java
  api/src/main/java/com/tago/api/trip/application/TripSaveService.java
  api/src/main/java/com/tago/api/trip/application/TripSearchService.java
  api/src/main/java/com/tago/api/trip/dto/request/TripCourseRecommendRequest.java
  api/src/main/java/com/tago/api/trip/dto/request/TripSaveRequest.java
  api/src/main/java/com/tago/api/trip/dto/response/TripSaveResponse.java
  api/src/main/java/com/tago/api/trip/presentation/TripGetApi.java
  api/src/main/java/com/tago/api/trip/presentation/TripSaveApi.java
  api/src/main/java/com/tago/api/tripmember/application/TripMemberDeleteService.java
  api/src/main/java/com/tago/api/tripmember/application/TripMemberGetService.java
  api/src/main/java/com/tago/api/tripmember/application/TripMemberSaveService.java
  api/src/main/resources/data.sql
  domain/src/main/java/com/tago/domain/course/domain/CoursePlace.java
  domain/src/main/java/com/tago/domain/course/handler/CourseQueryService.java
  domain/src/main/java/com/tago/domain/issue/handler/IssueCommandService.java
  domain/src/main/java/com/tago/domain/issue/service/IssueCreateService.java
  domain/src/main/java/com/tago/domain/member/domain/Member.java
  domain/src/main/java/com/tago/domain/member/domain/vo/MemberTags.java
  domain/src/main/java/com/tago/domain/member/handler/MemberCommandService.java
  domain/src/main/java/com/tago/domain/member/handler/MemberQueryService.java
  domain/src/main/java/com/tago/domain/member/service/MemberCreateService.java
  domain/src/main/java/com/tago/domain/member/service/MemberTagCreateService.java
  domain/src/main/java/com/tago/domain/member/service/MemberUpdateService.java
  domain/src/main/java/com/tago/domain/place/handler/PlaceQueryService.java
  domain/src/main/java/com/tago/domain/place/repository/PlaceCustomRepository.java
  domain/src/main/java/com/tago/domain/place/repository/impl/PlaceCustomRepositoryImpl.java
  domain/src/main/java/com/tago/domain/tag/handler/TagQueryService.java
  domain/src/main/java/com/tago/domain/tag/repository/TagCustomRepository.java
  domain/src/main/java/com/tago/domain/tag/repository/impl/TagCustomRepositoryImpl.java
  domain/src/main/java/com/tago/domain/trip/domain/Trip.java
  domain/src/main/java/com/tago/domain/trip/domain/TripPlace.java
  domain/src/main/java/com/tago/domain/trip/domain/TripTag.java
  domain/src/main/java/com/tago/domain/trip/dto/TripCreateDto.java
  domain/src/main/java/com/tago/domain/trip/handler/TripCommandService.java
  domain/src/main/java/com/tago/domain/trip/handler/TripPlaceQueryService.java
  domain/src/main/java/com/tago/domain/trip/handler/TripQueryService.java
  domain/src/main/java/com/tago/domain/trip/repository/TripCustomRepository.java
  domain/src/main/java/com/tago/domain/trip/repository/impl/TripCustomRepositoryImpl.java
  domain/src/main/java/com/tago/domain/trip/service/TripCreateService.java
  domain/src/main/java/com/tago/domain/trip/service/TripPlaceCreateService.java
  domain/src/main/java/com/tago/domain/trip/service/TripTagCreateService.java
  domain/src/main/java/com/tago/domain/tripmember/handler/TripMemberCommandService.java
  domain/src/main/java/com/tago/domain/tripmember/handler/TripMemberQueryService.java
  domain/src/main/java/com/tago/domain/tripmember/service/TripMemberCreateService.java
Labels: feature, refactor

#91 feat: 반려동물 정보 추가
  api/src/main/java/com/tago/api/common/mapper/TripStatusDtoMapper.java
  api/src/main/java/com/tago/api/trip/dto/response/TripStatusResponse.java
Labels: feature

#92 chore: CI/CD 구축
  .github/workflows/cd-dev.yml
  Dockerfile
  appspec.yml
  docker/Dockerfile
  docker/Dockerfile-elastic
  docker/docker-compose.elastic.yml
  docker/docker-compose.local.yml
  docker/docker-compose.yml
  scripts/afterInstall.sh
  scripts/beforeInstall.sh
Labels: chore

#93 fix: github action trigger branch 변경
  .github/workflows/cd-dev.yml
Labels: fix

#94 chore: Dockerfile 위치 변경
  .github/workflows/cd-dev.yml
  Dockerfile
  docker-compose.yml
Labels: chore

#95 chore: s3 bucket name 환경변수 설정
  .github/workflows/cd-dev.yml
Labels: chore

#97 feat: health check api 구현
  api/src/main/java/com/tago/api/common/config/SecurityConfig.java
  api/src/main/java/com/tago/api/common/healthCheck/healthCheckApi.java
Labels: feature
