Repository TraviTago/tago-api, pull requests merged in 2023-10, with the labels that each got.

#101 fix: place content_id 컬럼을 id 컬럼으로 변경
  api/src/main/java/com/tago/api/common/mapper/PlaceDtoMapper.java
  api/src/main/resources/data.sql
  api/src/main/resources/schema.sql
  domain/src/main/java/com/tago/domain/place/domain/Place.java
Labels: fix

#103 fix: trip 전체 조회 API 응답에 여행 참여 여부값 추가
  api/src/main/java/com/tago/api/common/mapper/TripDtoMapper.java
  api/src/main/java/com/tago/api/trip/application/TripGetService.java
  api/src/main/java/com/tago/api/trip/application/TripSearchService.java
  api/src/main/java/com/tago/api/trip/dto/response/MyTripGetResponse.java
  api/src/main/java/com/tago/api/trip/dto/response/TripGetResponse.java
  api/src/main/java/com/tago/api/trip/dto/response/TripStatusResponse.java
  api/src/main/java/com/tago/api/trip/presentation/TripGetApi.java
  api/src/main/java/com/tago/api/trip/presentation/TripSearchApi.java
  api/src/main/java/com/tago/api/tripmember/application/TripMemberGetService.java
  api/src/main/java/com/tago/api/tripmember/dto/response/TripMemberGetMemberResponse.java
  api/src/main/java/com/tago/api/tripmember/dto/response/TripMemberGetResponse.java
  api/src/main/java/com/tago/api/tripmember/presentation/TripMemberGetTripApi.java
  domain/src/main/java/com/tago/domain/trip/domain/Trip.java
  domain/src/main/java/com/tago/domain/trip/dto/TripRecommendDto.java
  domain/src/main/java/com/tago/domain/trip/handler/TripQueryService.java
  domain/src/main/java/com/tago/domain/trip/repository/TripCustomRepository.java
  domain/src/main/java/com/tago/domain/trip/repository/impl/TripCustomRepositoryImpl.java
  domain/src/main/java/com/tago/domain/tripmember/domain/TripMember.java
  domain/src/main/java/com/tago/domain/tripmember/dto/MyTripDto.java
  domain/src/main/java/com/tago/domain/tripmember/handler/TripMemberQueryService.java
  domain/src/main/java/com/tago/domain/tripmember/mapper/MyTripDtoMapper.java
  domain/src/main/java/com/tago/domain/tripmember/repository/TripMemberCustomRepository.java
  domain/src/main/java/com/tago/domain/tripmember/repository/impl/TripMemberCustomRepositoryImpl.java
Labels: refactor, fix

#105 chore: tomcat connection time 변경
  api/src/main/resources/application.yml
Labels: chore

#106 chore: keep alive 속성값 설정
  api/src/main/resources/application.yml
Labels: chore

#108 fix: place중복 오류 수정
  api/src/main/java/com/tago/api/common/mapper/CourseDtoMapper.java
  domain/src/main/java/com/tago/domain/course/repository/impl/CourseCustomRepositoryImpl.java
Labels: fix

#113 fix: 여행 나가기 API에 여행 참여 인원 감소 로직 추가
  api/src/main/java/com/tago/api/common/exception/AlreadyExistsTripMemberException.java
  api/src/main/java/com/tago/api/tripmember/application/TripMemberDeleteService.java
  api/src/main/java/com/tago/api/tripmember/application/TripMemberGetService.java
  api/src/main/java/com/tago/api/tripmember/application/TripMemberSaveService.java
  api/src/main/java/com/tago/api/tripmember/dto/response/TripMemberJoinResponse.java
  api/src/main/java/com/tago/api/tripmember/presentation/TripMemberDeleteApi.java
  api/src/main/java/com/tago/api/tripmember/presentation/TripMemberSaveApi.java
  domain/src/main/java/com/tago/domain/common/error/ErrorCode.java
  domain/src/main/java/com/tago/domain/trip/domain/Trip.java
  domain/src/main/java/com/tago/domain/trip/handler/TripQueryService.java
  domain/src/main/java/com/tago/domain/trip/repository/TripCustomRepository.java
  domain/src/main/java/com/tago/domain/trip/repository/impl/TripCustomRepositoryImpl.java
Labels: fix

#114 fix: 여행 추천 시 여행 존재하지 않는 경우 랜덤하게 trip 반환
  domain/src/main/java/com/tago/domain/course/repository/impl/CourseCustomRepositoryImpl.java
  domain/src/main/java/com/tago/domain/trip/handler/TripQueryService.java
  domain/src/main/java/com/tago/domain/trip/repository/impl/TripCustomRepositoryImpl.java
Labels: fix

#120 fix: trip 페이지네이션 404 에러 제거
  domain/src/main/java/com/tago/domain/trip/handler/TripQueryService.java
Labels: fix

#125 feat: 택시기사 로그인 API 구현
  api/src/main/java/com/tago/api/common/config/SecurityConfig.java
  api/src/main/java/com/tago/api/common/security/jwt/filter/AuthorizationHeaderTokenResolver.java
  api/src/main/java/com/tago/api/driver/application/DriverAuthService.java
  api/src/main/java/com/tago/api/driver/dto/request/LoginRequest.java
  api/src/main/java/com/tago/api/driver/dto/response/LoginResponse.java
  api/src/main/java/com/tago/api/driver/presentation/DriverAuthApi.java
  domain/src/main/java/com/tago/domain/common/error/ErrorCode.java
  domain/src/main/java/com/tago/domain/driver/exception/CarNotFoundException.java
  domain/src/main/java/com/tago/domain/driver/exception/DispatchNotFoundException.java
  domain/src/main/java/com/tago/domain/driver/exception/DriverNotFoundException.java
  domain/src/main/java/com/tago/domain/driver/handler/DriverQueryService.java
  domain/src/main/java/com/tago/domain/driver/repository/CarRepository.java
  domain/src/main/java/com/tago/domain/driver/repository/DispatchRepository.java
  domain/src/main/java/com/tago/domain/driver/repository/DriverRepository.java
Labels: feature

#126 feat: 코스 운행 수락/취소 API 구현
  api/src/main/java/com/tago/api/common/config/WebMvcConfig.java
  api/src/main/java/com/tago/api/driver/application/DriverDispatchService.java
  api/src/main/java/com/tago/api/driver/presentation/DriverDispatchApi.java
  api/src/main/java/com/tago/api/member/application/MemberService.java
  api/src/main/java/com/tago/api/trip/application/TripGetService.java
  domain/src/main/java/com/tago/domain/driver/handler/DispatchCommandService.java
  domain/src/main/java/com/tago/domain/driver/handler/DispatchQueryService.java
  domain/src/main/java/com/tago/domain/driver/repository/DispatchRepository.java
  domain/src/main/java/com/tago/domain/driver/service/DispatchCreateService.java
  domain/src/main/java/com/tago/domain/driver/service/DispatchDeleteService.java
  domain/src/main/java/com/tago/domain/driver/service/factory/dispatch/DispatchService.java
  domain/src/main/java/com/tago/domain/driver/service/factory/dispatch/DispatchServiceFactory.java
  domain/src/main/java/com/tago/domain/member/handler/MemberQueryService.java
  domain/src/main/java/com/tago/domain/member/repository/MemberCustomRepository.java
  domain/src/main/java/com/tago/domain/member/repository/impl/MemberCustomRepositoryImpl.java
  domain/src/main/java/com/tago/domain/member/service/MemberUpdateService.java
Labels: feature

#127 feat: 택시기사 여행 및 정보 조회 API 구현
  api/src/main/java/com/tago/api/common/mapper/DriverTripDtoMapper.java
  api/src/main/java/com/tago/api/driver/application/DriverService.java
  api/src/main/java/com/tago/api/driver/application/DriverTripService.java
  api/src/main/java/com/tago/api/driver/dto/response/DriverGetResponse.java
  api/src/main/java/com/tago/api/driver/dto/response/DriverTripResponse.java
  api/src/main/java/com/tago/api/driver/dto/response/TripGetResponse.java
  api/src/main/java/com/tago/api/driver/presentation/DriverApi.java
  api/src/main/java/com/tago/api/driver/presentation/DriverDispatchApi.java
  api/src/main/java/com/tago/api/driver/presentation/DriverTripApi.java
  api/src/main/java/com/tago/api/trip/presentation/TripGetApi.java
  domain/src/main/java/com/tago/domain/common/error/ErrorCode.java
  domain/src/main/java/com/tago/domain/driver/domain/Driver.java
  domain/src/main/java/com/tago/domain/driver/domain/vo/DriverInfo.java
  domain/src/main/java/com/tago/domain/driver/dto/DriverInfoDto.java
  domain/src/main/java/com/tago/domain/driver/exception/AlreadyExistsDispatchException.java
  domain/src/main/java/com/tago/domain/driver/handler/DispatchQueryService.java
  domain/src/main/java/com/tago/domain/driver/handler/DriverQueryService.java
  domain/src/main/java/com/tago/domain/driver/repository/DispatchRepository.java
  domain/src/main/java/com/tago/domain/driver/repository/DriverCustomRepository.java
  domain/src/main/java/com/tago/domain/driver/repository/DriverRepository.java
  domain/src/main/java/com/tago/domain/driver/repository/impl/DriverCustomRepositoryImpl.java
  domain/src/main/java/com/tago/domain/driver/service/DispatchCreateService.java
  domain/src/main/java/com/tago/domain/trip/handler/TripQueryService.java
  domain/src/main/java/com/tago/domain/trip/repository/TripCustomRepository.java
  domain/src/main/java/com/tago/domain/trip/repository/impl/TripCustomRepositoryImpl.java
Labels: feature

#129 fix: 동성만 필터 여행 전체 조회 쿼리 수정
  api/src/main/java/com/tago/api/trip/application/TripGetService.java
  domain/src/main/java/com/tago/domain/trip/handler/TripQueryService.java
  domain/src/main/java/com/tago/domain/trip/repository/TripCustomRepository.java
  domain/src/main/java/com/tago/domain/trip/repository/impl/TripCustomRepositoryImpl.java
Labels: fix

#131 chore: beforeInstall hook 제거
  appspec.yml
Labels: chore

#133 fix: 지난 여행추천 오류 해결
  domain/src/main/java/com/tago/domain/trip/domain/Trip.java
  domain/src/main/java/com/tago/domain/trip/repository/impl/TripCustomRepositoryImpl.java
Labels: fix

#135 fix: 쿼리 조건 수정
  domain/src/main/java/com/tago/domain/trip/repository/impl/TripCustomRepositoryImpl.java
Labels: fix

#140 feat: 기사님 토큰 재발급 API 구현
  api/src/main/java/com/tago/api/driver/application/DriverTripService.java
  api/src/main/java/com/tago/api/driver/dto/response/DriverTripGetAllResponse.java
  api/src/main/java/com/tago/api/driver/dto/response/TripGetOneResponse.java
  api/src/main/java/com/tago/api/driver/dto/response/TripGetResponse.java
  api/src/main/java/com/tago/api/driver/presentation/DriverAuthApi.java
  api/src/main/java/com/tago/api/driver/presentation/DriverTripApi.java
  domain/src/main/java/com/tago/domain/driver/handler/DispatchQueryService.java
  domain/src/main/java/com/tago/domain/driver/repository/DispatchRepository.java
Labels: feature

#143 fix: sms 인증 문자 형식 수정
  api/src/main/java/com/tago/api/infra/sms/infra/ncloud/NcloudSmsClient.java
  domain/src/main/java/com/tago/domain/trip/repository/impl/TripCustomRepositoryImpl.java
Labels: fix

#144 fix: 종료된 여행은 제외되도록 Trip 추천 쿼리 수정
  domain/src/main/java/com/tago/domain/trip/repository/impl/TripCustomRepositoryImpl.java
Labels: fix

#145 fix: trip 추천 쿼리 수정
  domain/src/main/java/com/tago/domain/trip/repository/impl/TripCustomRepositoryImpl.java
Labels: fix

#149 fix: driver 정보 조회 API 권한 수정
  api/src/main/java/com/tago/api/driver/application/DriverService.java
  api/src/main/java/com/tago/api/driver/presentation/DriverApi.java
  domain/src/main/java/com/tago/domain/driver/handler/DispatchQueryService.java
  domain/src/main/java/com/tago/domain/driver/handler/DriverQueryService.java
  domain/src/main/java/com/tago/domain/driver/repository/DriverCustomRepository.java
  domain/src/main/java/com/tago/domain/driver/repository/impl/DriverCustomRepositoryImpl.java
Labels: fix

#150 Feat: 타고가 제안하는 여행 api를 구현한다
  api/src/main/java/com/tago/api/trip/application/TripGetService.java
  api/src/main/java/com/tago/api/trip/dto/response/TagoTripOneResponse.java
  api/src/main/java/com/tago/api/trip/dto/response/TagoTripResponse.java
  api/src/main/java/com/tago/api/trip/presentation/TripGetApi.java
  domain/src/main/java/com/tago/domain/trip/domain/TagoTrip.java
  domain/src/main/java/com/tago/domain/trip/domain/Trip.java
  domain/src/main/java/com/tago/domain/trip/dto/TagoTripOneDto.java
  domain/src/main/java/com/tago/domain/trip/handler/TripQueryService.java
  domain/src/main/java/com/tago/domain/trip/repository/TagoTripRepository.java
  domain/src/main/java/com/tago/domain/trip/repository/TripCustomRepository.java
  domain/src/main/java/com/tago/domain/trip/repository/TripPlaceCustomRepository.java
  domain/src/main/java/com/tago/domain/trip/repository/TripRepository.java
Labels: feature

#157 fix: place조회 순서 변경
  domain/src/main/java/com/tago/domain/place/repository/impl/PlaceCustomRepositoryImpl.java
Labels: fix

#159 chore: fcm 환경변수 추가
  docker-compose.yml
Labels: chore

#162 fix: verify-code API 응답에 회원가입 여부 추가
  api/src/main/java/com/tago/api/infra/fcm/FCMClient.java
  api/src/main/java/com/tago/api/infra/fcm/FCMSendDto.java
  api/src/main/java/com/tago/api/infra/fcm/FCMService.java
  api/src/main/java/com/tago/api/infra/fcm/FCMType.java
  api/src/main/java/com/tago/api/infra/sms/application/SmsService.java
  api/src/main/java/com/tago/api/infra/sms/domain/dto/SmsResponse.java
  domain/src/main/java/com/tago/domain/driver/event/producer/DispatchEvent.java
  domain/src/main/java/com/tago/domain/driver/service/DispatchCreateService.java
  domain/src/main/java/com/tago/domain/member/handler/MemberQueryService.java
  domain/src/main/java/com/tago/domain/member/repository/MemberRepository.java
  domain/src/main/java/com/tago/domain/trip/domain/Trip.java
  domain/src/main/java/com/tago/domain/tripmember/event/producer/TripMemberEvent.java
  domain/src/main/java/com/tago/domain/tripmember/service/TripMemberCreateService.java
  domain/src/main/java/com/tago/domain/tripmember/service/TripMemberDeleteService.java
Labels: fix

#164 feat: 타고가 제안한 여행 생성 scheduler 구현
  api/src/main/java/com/tago/api/ApiApplication.java
  api/src/main/java/com/tago/api/auth/dto/request/SignUpRequest.java
  api/src/main/java/com/tago/api/common/mapper/MemberDtoMapper.java
  api/src/main/java/com/tago/api/common/mapper/OriginTripDtoMapper.java
  api/src/main/java/com/tago/api/course/application/CourseService.java
  api/src/main/java/com/tago/api/member/dto/request/MemberUpdateRequest.java
  api/src/main/java/com/tago/api/trip/application/OriginTripGetService.java
  api/src/main/java/com/tago/api/trip/application/TripGetService.java
  api/src/main/java/com/tago/api/trip/application/TripManageService.java
  api/src/main/java/com/tago/api/trip/dto/request/TripSaveRequest.java
  api/src/main/java/com/tago/api/trip/dto/response/OriginTripGetAllResponse.java
  api/src/main/java/com/tago/api/trip/dto/response/OriginTripGetResponse.java
  api/src/main/java/com/tago/api/trip/dto/response/TagoTripOneResponse.java
  api/src/main/java/com/tago/api/trip/dto/response/TagoTripResponse.java
  api/src/main/java/com/tago/api/trip/presentation/OriginTripGetApi.java
  api/src/main/java/com/tago/api/trip/presentation/TripGetApi.java
  api/src/main/java/com/tago/api/trip/scheduler/TripScheduler.java
  api/src/main/java/com/tago/api/trip/scheduler/job/TripJob.java
  api/src/main/java/com/tago/api/trip/scheduler/job/TripJobFactory.java
  api/src/main/java/com/tago/api/trip/scheduler/job/TripJobType.java
  api/src/main/java/com/tago/api/trip/scheduler/job/impl/OriginTripCreateJob.java
  domain/src/main/java/com/tago/domain/common/converter/FavoriteEnumArrayConverter.java
  domain/src/main/java/com/tago/domain/common/entity/CSVToMySQL.java
  domain/src/main/java/com/tago/domain/common/error/ErrorCode.java
  domain/src/main/java/com/tago/domain/common/model/entity/BaseTimeEntity.java
  domain/src/main/java/com/tago/domain/course/handler/CourseQueryService.java
  domain/src/main/java/com/tago/domain/course/repository/CourseCustomRepository.java
  domain/src/main/java/com/tago/domain/course/repository/impl/CourseCustomRepositoryImpl.java
  domain/src/main/java/com/tago/domain/member/domain/Member.java
  domain/src/main/java/com/tago/domain/member/dto/MemberCreateDto.java
  domain/src/main/java/com/tago/domain/member/dto/MemberUpdateDto.java
  domain/src/main/java/com/tago/domain/member/service/MemberCreateService.java
  domain/src/main/java/com/tago/domain/member/service/MemberTagCreateService.java
  domain/src/main/java/com/tago/domain/member/service/MemberUpdateService.java
  domain/src/main/java/com/tago/domain/tag/domain/Tag.java
  domain/src/main/java/com/tago/domain/tag/domain/vo/TagType.java
  domain/src/main/java/com/tago/domain/tag/handler/TagQueryService.java
  domain/src/main/java/com/tago/domain/tag/repository/TagCustomRepository.java
  domain/src/main/java/com/tago/domain/tag/repository/TagRepository.java
  domain/src/main/java/com/tago/domain/tag/repository/impl/TagCustomRepositoryImpl.java
  domain/src/main/java/com/tago/domain/trip/domain/OriginTrip.java
  domain/src/main/java/com/tago/domain/trip/domain/TagoTrip.java
  domain/src/main/java/com/tago/domain/trip/domain/Trip.java
  domain/src/main/java/com/tago/domain/trip/dto/OriginTripCreateDto.java
  domain/src/main/java/com/tago/domain/trip/dto/TagoTripOneDto.java
  domain/src/main/java/com/tago/domain/trip/dto/TripCreateDto.java
  domain/src/main/java/com/tago/domain/trip/exception/OriginTripNotFoundException.java
  domain/src/main/java/com/tago/domain/trip/handler/OriginTripQueryService.java
  domain/src/main/java/com/tago/domain/trip/handler/TripQueryService.java
  domain/src/main/java/com/tago/domain/trip/repository/OriginTripJdbcRepository.java
  domain/src/main/java/com/tago/domain/trip/repository/OriginTripRepository.java
  domain/src/main/java/com/tago/domain/trip/repository/TagoTripRepository.java
  domain/src/main/java/com/tago/domain/trip/repository/TripCustomRepository.java
  domain/src/main/java/com/tago/domain/trip/repository/TripRepository.java
  domain/src/main/java/com/tago/domain/trip/repository/impl/OriginTripJdbcRepositoryImpl.java
  domain/src/main/java/com/tago/domain/trip/repository/impl/TripCustomRepositoryImpl.java
  domain/src/main/java/com/tago/domain/trip/service/OriginTripCreateService.java
  domain/src/main/java/com/tago/domain/trip/service/TripCreateService.java
  domain/src/main/java/com/tago/domain/trip/service/TripTagCreateService.java
Labels: feature

#166 feat: 여행지 이름으로 조회하는 api구현한다
  api/src/main/java/com/tago/api/place/application/PlaceService.java
  api/src/main/java/com/tago/api/place/presentation/PlaceApi.java
  domain/src/main/java/com/tago/domain/place/handler/PlaceQueryService.java
  domain/src/main/java/com/tago/domain/place/repository/PlaceRepository.java
Labels: feature

#168 fix: trip 전체 조회 pet 필터 조건 수정
  domain/src/main/java/com/tago/domain/course/repository/impl/CourseCustomRepositoryImpl.java
  domain/src/main/java/com/tago/domain/trip/repository/impl/OriginTripJdbcRepositoryImpl.java
  domain/src/main/java/com/tago/domain/trip/repository/impl/TripCustomRepositoryImpl.java
Labels: fix

#169 chore: redis 컨테이너 삭제 및 Elasticache host 연결
  docker-compose.yml
Labels: chore

#170 feat: 여행생성자는 탈퇴 불가능하도록 조건 추가
  api/src/main/java/com/tago/api/auth/application/AuthService.java
  domain/src/main/java/com/tago/domain/trip/repository/TripRepository.java
Labels: feature

#171 feat: 타고가 제안한 여행 trip_place Bulk Insert 구현
  api/src/main/java/com/tago/api/infra/fcm/FCMTokenUtil.java
  api/src/main/java/com/tago/api/infra/sms/util/VerificationCodeUtil.java
  api/src/main/java/com/tago/api/trip/dto/request/TripSaveRequest.java
  domain/build.gradle
  domain/src/main/java/com/tago/domain/trip/domain/TripPlace.java
  domain/src/main/java/com/tago/domain/trip/dto/OriginTripCreateDto.java
  domain/src/main/java/com/tago/domain/trip/dto/OriginTripPlaceCreateDto.java
  domain/src/main/java/com/tago/domain/trip/repository/OriginTripJdbcRepository.java
  domain/src/main/java/com/tago/domain/trip/repository/impl/OriginTripJdbcRepositoryImpl.java
  domain/src/main/java/com/tago/domain/trip/service/OriginTripCreateService.java
Labels: feature

#174 fix: 타고가 제안한 여행 scheduler cron 변경
  api/src/main/java/com/tago/api/common/mapper/MyTripDtoMapper.java
  api/src/main/java/com/tago/api/trip/application/TripGetService.java
  api/src/main/java/com/tago/api/trip/scheduler/TripScheduler.java
  domain/src/main/java/com/tago/domain/trip/service/OriginTripCreateService.java
  domain/src/test/java/com/tago/domain/OriginTripBulkInsertTest.java
  domain/src/test/java/com/tago/domain/TestConfig.java
  domain/src/test/resources/application-h2.yml
  domain/src/test/resources/application-mysql.yml
Labels: fix

#176 fix: 이미 참여 중인 여행은 추천 안되도록 쿼리 수정
  api/src/main/java/com/tago/api/trip/application/OriginTripGetService.java
  api/src/main/java/com/tago/api/trip/application/TripGetService.java
  domain/src/main/java/com/tago/domain/trip/handler/TripQueryService.java
  domain/src/main/java/com/tago/domain/trip/repository/TripCustomRepository.java
  domain/src/main/java/com/tago/domain/trip/repository/TripRepository.java
  domain/src/main/java/com/tago/domain/trip/repository/impl/TripCustomRepositoryImpl.java
Labels: fix

#177 fix: 여행 참여하기 transactional 어노테이션 import 경로 수정
  api/src/main/java/com/tago/api/tripmember/application/TripMemberSaveService.java
Labels: fix
